from __future__ import annotations

import os
from pathlib import Path

os.environ["NO_PROXY"] = "127.0.0.1,localhost,::1"
os.environ["no_proxy"] = "127.0.0.1,localhost,::1"

PACKAGE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = PACKAGE_DIR.parent

DETAILED_LOG_DIR = PACKAGE_DIR / "logs"
GENERAL_LOG_DIR = PROJECT_ROOT / "logs"

DATA_DIR = Path("data")
STATE_DIR = DATA_DIR / "_state"
DATASET_DIR = Path(os.getenv("DATASET_DIR", "dataset"))

DISCOVERED_FILE = STATE_DIR / "discovered_urls.jsonl"
ERRORS_FILE = STATE_DIR / "errors.jsonl"

SITE_ERROR_LIMIT = int(os.getenv("SITE_ERROR_LIMIT", "4"))

PLAYWRIGHT_HEADLESS = os.getenv("PLAYWRIGHT_HEADLESS", "true").lower() == "true"
PLAYWRIGHT_TIMEOUT_MS = int(os.getenv("PLAYWRIGHT_TIMEOUT_MS", "30000"))

VPN_SITES = {
    "simplicity",
    "etsy",
    "marfy",
    # "vikisews", если потом понадобится
}

ETSY_QUERIES = {
    "etsy_vogue_dresses": "vogue sewing pattern dress",
    "etsy_vogue_tops": "vogue sewing pattern top",
    "etsy_vogue_blouses": "vogue sewing pattern blouse",
    "etsy_vogue_shirts": "vogue sewing pattern shirt",
    "etsy_vogue_skirts": "vogue sewing pattern skirt",
    "etsy_vogue_pants": "vogue sewing pattern pants",
    "etsy_vogue_shorts": "vogue sewing pattern shorts",
    "etsy_vogue_jackets": "vogue sewing pattern jacket",
    "etsy_vogue_vests": "vogue sewing pattern vest",
    "etsy_vogue_jumpsuits": "vogue sewing pattern jumpsuit",
    "etsy_vogue_outerwear": "vogue sewing pattern coat",
    "etsy_vogue_women": "vogue sewing pattern womens",
    "etsy_vogue_men": "vogue sewing pattern mens",
}

SITE_SPECS: dict[str, dict] = {
    "simplicity_women": {
        "type": "browser",
        "handler": "simplicity",
        "site": "simplicity",
        "start_url": "https://simplicity.com/women-patterns/",
        "category": "women-patterns",
    },
    "simplicity_men": {
        "type": "browser",
        "handler": "simplicity",
        "site": "simplicity",
        "start_url": "https://simplicity.com/men-patterns/",
        "category": "men-patterns",
    },

    "vikisews_dresses": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/platja-i-sarafany/",
        "category": "platja-i-sarafany",
    },
    "vikisews_tops": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/khudi-futbolki-longslivy/",
        "category": "khudi-futbolki-longslivy",
    },
    "vikisews_pants": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/bryuki-dzhinsy-shorty/",
        "category": "bryuki-dzhinsy-shorty",
    },
    "vikisews_shirts": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/rubashki-bluzki-korsazhi/",
        "category": "rubashki-bluzki-korsazhi",
    },
    "vikisews_skirts": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/jubki/",
        "category": "jubki",
    },
    "vikisews_jackets": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/zhakety-kardigany-zhilety/",
        "category": "zhakety-kardigany-zhilety",
    },
    "vikisews_overalls": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/kombinezony/",
        "category": "kombinezony",
    },
    "vikisews_outerwear": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/verhnjaja-odezhda/",
        "category": "verhnjaja-odezhda",
    },
    "vikisews_homewear": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/belye-domashnyaya-odezhda/",
        "category": "belye-domashnyaya-odezhda",
    },
    "vikisews_men": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/muzhskie-vykrojki/",
        "category": "muzhskie-vykrojki",
    },

    "shkatulka_dresses": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/platya/",
        "category": "platya",
        "section_gender": "women",
    },
    "shkatulka_tops": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bluzki-topy/",
        "category": "bluzki-topy",
        "section_gender": "women",
    },
    "shkatulka_pants": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bryuki1/",
        "category": "bryuki1",
        "section_gender": "women",
    },
    "shkatulka_skirts": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/yubki-2/",
        "category": "yubki-2",
        "section_gender": "women",
    },
    "shkatulka_hoodies": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/tolstovki-svitshoty-hudi/",
        "category": "tolstovki-svitshoty-hudi",
        "section_gender": "women",
    },
    "shkatulka_outerwear": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/verhnyaya-odejda/",
        "category": "verhnyaya-odejda",
        "section_gender": "women",
    },
    "shkatulka_jackets": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/jakety-jilety/",
        "category": "jakety-jilety",
        "section_gender": "women",
    },
    "shkatulka_overalls": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/kombinezony-polukombinezony/",
        "category": "kombinezony-polukombinezony",
        "section_gender": "women",
    },
    "shkatulka_homewear_women": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bele-kupalniki-domashnyaya-odejda/",
        "category": "bele-kupalniki-domashnyaya-odezhda",
        "section_gender": "women",
    },
    "shkatulka_homewear_men": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bele-domashnyaya-odejda/",
        "category": "bele-domashnyaya-odezhda",
        "section_gender": "men",
    },
    "shkatulka_men_shirts": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/rubashki-futbolki/",
        "category": "rubashki-futbolki",
        "section_gender": "men",
    },
    "shkatulka_men_hoodies": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/tolstovki-hudi-2/",
        "category": "tolstovki-hudi-2",
        "section_gender": "men",
    },
    "shkatulka_men_pants": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bryuki-shorty/",
        "category": "bryuki-shorty",
        "section_gender": "men",
    },
    "shkatulka_men_outerwear": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/verhnyaya-odejda-3/",
        "category": "verhnyaya-odejda-3",
        "section_gender": "men",
    },
    "shkatulka_men_jackets": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/jilety-pidjaki/",
        "category": "jilety-pidjaki",
        "section_gender": "men",
    },

    # --- NEW: MARFY ---
    "marfy_handmade_precut": {
        "type": "browser",
        "handler": "marfy",
        "site": "marfy",
        "start_url": "https://www.marfy.it/en/the-marfy-hand-made-pre-cut-sewing-pattern/",
        "category": "the-marfy-hand-made-pre-cut-sewing-pattern",
        "page_from": 1,
        "page_to": 108,
    },

    # --- NEW: ETSY ---
    "etsy_vogue_dresses": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+dress&ref=search_bar",
        "category": "vogue-dresses",
        "query": ETSY_QUERIES["etsy_vogue_dresses"],
    },
    "etsy_vogue_tops": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+top&ref=search_bar",
        "category": "vogue-tops",
        "query": ETSY_QUERIES["etsy_vogue_tops"],
    },
    "etsy_vogue_blouses": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+blouse&ref=search_bar",
        "category": "vogue-blouses",
        "query": ETSY_QUERIES["etsy_vogue_blouses"],
    },
    "etsy_vogue_shirts": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+shirt&ref=search_bar",
        "category": "vogue-shirts",
        "query": ETSY_QUERIES["etsy_vogue_shirts"],
    },
    "etsy_vogue_skirts": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+skirt&ref=search_bar",
        "category": "vogue-skirts",
        "query": ETSY_QUERIES["etsy_vogue_skirts"],
    },
    "etsy_vogue_pants": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+pants&ref=search_bar",
        "category": "vogue-pants",
        "query": ETSY_QUERIES["etsy_vogue_pants"],
    },
    "etsy_vogue_shorts": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+shorts&ref=search_bar",
        "category": "vogue-shorts",
        "query": ETSY_QUERIES["etsy_vogue_shorts"],
    },
    "etsy_vogue_jackets": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+jacket&ref=search_bar",
        "category": "vogue-jackets",
        "query": ETSY_QUERIES["etsy_vogue_jackets"],
    },
    "etsy_vogue_vests": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+vest&ref=search_bar",
        "category": "vogue-vests",
        "query": ETSY_QUERIES["etsy_vogue_vests"],
    },
    "etsy_vogue_jumpsuits": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+jumpsuit&ref=search_bar",
        "category": "vogue-jumpsuits",
        "query": ETSY_QUERIES["etsy_vogue_jumpsuits"],
    },
    "etsy_vogue_outerwear": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+coat&ref=search_bar",
        "category": "vogue-outerwear",
        "query": ETSY_QUERIES["etsy_vogue_outerwear"],
    },
    "etsy_vogue_women": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+womens&ref=search_bar",
        "category": "vogue-women",
        "query": ETSY_QUERIES["etsy_vogue_women"],
    },
    "etsy_vogue_men": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": "https://www.etsy.com/search?q=vogue+sewing+pattern+mens&ref=search_bar",
        "category": "vogue-men",
        "query": ETSY_QUERIES["etsy_vogue_men"],
    },

    # --- NEW: BURDASTYLE ---
    "burdastyle_women_dresses": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/platya-dlya-zhenshhin/",
        "category": "platya-dlya-zhenshhin",
    },
    "burdastyle_women_tops": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/topy-dlya-zhenshhin/",
        "category": "topy-dlya-zhenshhin",
    },
    "burdastyle_women_bolero": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/bolero-dlya-zhenshhin/",
        "category": "bolero-dlya-zhenshhin",
    },
    "burdastyle_women_shirts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/rubashki-dlya-zhenshhin/",
        "category": "rubashki-dlya-zhenshhin",
    },
    "burdastyle_women_sweaters": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/svitery-dlya-zhenshhin/",
        "category": "svitery-dlya-zhenshhin",
    },
    "burdastyle_women_blazers": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/pidzhaki-dlya-zhenshhin/",
        "category": "pidzhaki-dlya-zhenshhin",
    },
    "burdastyle_women_vests": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/zhilety-dlya-zhenshhin/",
        "category": "zhilety-dlya-zhenshhin",
    },
    "burdastyle_women_skirts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/yubki-dlya-zhenshhin/",
        "category": "yubki-dlya-zhenshhin",
    },
    "burdastyle_women_pants": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/bryuki-dlya-zhenshhin/",
        "category": "bryuki-dlya-zhenshhin",
    },
    "burdastyle_women_shorts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/shorty-dlya-zhenshhin/",
        "category": "shorty-dlya-zhenshhin",
    },
    "burdastyle_women_overalls": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/kombinezony-dlya-zhenshhin/",
        "category": "kombinezony-dlya-zhenshhin",
    },
    "burdastyle_women_suits": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/komplekty-i-kostyumy-dlya-zhenshhin/",
        "category": "komplekty-i-kostyumy-dlya-zhenshhin",
    },
    "burdastyle_women_outerwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/verkhnyaya-odezhda-dlya-zhenshhin/",
        "category": "verkhnyaya-odezhda-dlya-zhenshhin",
    },
    "burdastyle_women_underwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/nizhnee-bele-dlya-zhenshhin/",
        "category": "nizhnee-bele-dlya-zhenshhin",
    },
    "burdastyle_women_swimwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/kupalniki-dlya-zhenshhin/",
        "category": "kupalniki-dlya-zhenshhin",
    },
    "burdastyle_women_homewear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/odezhda-dlya-doma-dlya-zhenshhin/",
        "category": "odezhda-dlya-doma-dlya-zhenshhin",
    },
    "burdastyle_men_shirts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/rubashki-dlya-muzhchin/",
        "category": "rubashki-dlya-muzhchin",
    },
    "burdastyle_men_sweaters": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/svitery-dlya-muzhchin/",
        "category": "svitery-dlya-muzhchin",
    },
    "burdastyle_men_blazers": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/pidzhaki-dlya-muzhchin/",
        "category": "pidzhaki-dlya-muzhchin",
    },
    "burdastyle_men_vests": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/zhilety-dlya-muzhchin/",
        "category": "zhilety-dlya-muzhchin",
    },
    "burdastyle_men_pants": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/bryuki-dlya-muzhchin/",
        "category": "bryuki-dlya-muzhchin",
    },
    "burdastyle_men_shorts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/shorty-dlya-muzhchin/",
        "category": "shorty-dlya-muzhchin",
    },
    "burdastyle_men_overalls": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/kombinezony-dlya-muzhchin/",
        "category": "kombinezony-dlya-muzhchin",
    },
    "burdastyle_men_suits": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/komplekty-i-kostyumy-dlya-muzhchin/",
        "category": "komplekty-i-kostyumy-dlya-muzhchin",
    },
    "burdastyle_men_outerwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/verkhnyaya-odezhda-dlya-muzhchin/",
        "category": "verkhnyaya-odezhda-dlya-muzhchin",
    },
    "burdastyle_men_underwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/nizhnee-bele-dlya-muzhchin/",
        "category": "nizhnee-bele-dlya-muzhchin",
    },

    # --- NEW: HELPERSEW ---
    "helpersew_women": {
        "type": "browser",
        "handler": "helpersew",
        "site": "helpersew",
        "start_url": "https://helpersew.com/catalog/zhenskie/",
        "category": "zhenskie",
    },
    "helpersew_men": {
        "type": "browser",
        "handler": "helpersew",
        "site": "helpersew",
        "start_url": "https://helpersew.com/catalog/muzhskie/",
        "category": "muzhskie",
    },

    # --- NEW: GRASSER ---
    "grasser_women": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/vykrojki-dlya-zhenshchin/",
        "category": "vykrojki-dlya-zhenshchin",
        "page_param": "PAGEN_3",
        "page_from": 1,
        "page_to": 32,
    },
    "grasser_men": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/muzhskie-vykrojki/",
        "category": "muzhskie-vykrojki",
        "page_param": "PAGEN_3",
        "page_from": 1,
        "page_to": 3,
    },
}

SPEC_GROUPS: dict[str, set[str]] = {
    "current_all": {
        "simplicity_women",
        "simplicity_men",

        "vikisews_dresses",
        "vikisews_tops",
        "vikisews_pants",
        "vikisews_shirts",
        "vikisews_skirts",
        "vikisews_jackets",
        "vikisews_overalls",
        "vikisews_outerwear",
        "vikisews_homewear",
        "vikisews_men",

        "shkatulka_dresses",
        "shkatulka_tops",
        "shkatulka_pants",
        "shkatulka_skirts",
        "shkatulka_hoodies",
        "shkatulka_outerwear",
        "shkatulka_jackets",
        "shkatulka_overalls",
        "shkatulka_homewear_women",
        "shkatulka_homewear_men",
        "shkatulka_men_shirts",
        "shkatulka_men_hoodies",
        "shkatulka_men_pants",
        "shkatulka_men_outerwear",
        "shkatulka_men_jackets",
    },

    "vpn_new": {
        "marfy_handmade_precut",

        "etsy_vogue_dresses",
        "etsy_vogue_tops",
        "etsy_vogue_blouses",
        "etsy_vogue_shirts",
        "etsy_vogue_skirts",
        "etsy_vogue_pants",
        "etsy_vogue_shorts",
        "etsy_vogue_jackets",
        "etsy_vogue_vests",
        "etsy_vogue_jumpsuits",
        "etsy_vogue_outerwear",
        "etsy_vogue_women",
        "etsy_vogue_men",
    },

    "novpn_new": {
        "burdastyle_women_dresses",
        "burdastyle_women_tops",
        "burdastyle_women_bolero",
        "burdastyle_women_shirts",
        "burdastyle_women_sweaters",
        "burdastyle_women_blazers",
        "burdastyle_women_vests",
        "burdastyle_women_skirts",
        "burdastyle_women_pants",
        "burdastyle_women_shorts",
        "burdastyle_women_overalls",
        "burdastyle_women_suits",
        "burdastyle_women_outerwear",
        "burdastyle_women_underwear",
        "burdastyle_women_swimwear",
        "burdastyle_women_homewear",

        "burdastyle_men_shirts",
        "burdastyle_men_sweaters",
        "burdastyle_men_blazers",
        "burdastyle_men_vests",
        "burdastyle_men_pants",
        "burdastyle_men_shorts",
        "burdastyle_men_overalls",
        "burdastyle_men_suits",
        "burdastyle_men_outerwear",
        "burdastyle_men_underwear",

        "helpersew_women",
        "helpersew_men",

        "grasser_women",
        "grasser_men",
    },

    "etsy_all": {
        "etsy_vogue_dresses",
        "etsy_vogue_tops",
        "etsy_vogue_blouses",
        "etsy_vogue_shirts",
        "etsy_vogue_skirts",
        "etsy_vogue_pants",
        "etsy_vogue_shorts",
        "etsy_vogue_jackets",
        "etsy_vogue_vests",
        "etsy_vogue_jumpsuits",
        "etsy_vogue_outerwear",
        "etsy_vogue_women",
        "etsy_vogue_men",
    },

    "burdastyle_women_all": {
        "burdastyle_women_dresses",
        "burdastyle_women_tops",
        "burdastyle_women_bolero",
        "burdastyle_women_shirts",
        "burdastyle_women_sweaters",
        "burdastyle_women_blazers",
        "burdastyle_women_vests",
        "burdastyle_women_skirts",
        "burdastyle_women_pants",
        "burdastyle_women_shorts",
        "burdastyle_women_overalls",
        "burdastyle_women_suits",
        "burdastyle_women_outerwear",
        "burdastyle_women_underwear",
        "burdastyle_women_swimwear",
        "burdastyle_women_homewear",
    },

    "burdastyle_men_all": {
        "burdastyle_men_shirts",
        "burdastyle_men_sweaters",
        "burdastyle_men_blazers",
        "burdastyle_men_vests",
        "burdastyle_men_pants",
        "burdastyle_men_shorts",
        "burdastyle_men_overalls",
        "burdastyle_men_suits",
        "burdastyle_men_outerwear",
        "burdastyle_men_underwear",
    },

    "helpersew_all": {
        "helpersew_women",
        "helpersew_men",
    },

    "grasser_all": {
        "grasser_women",
        "grasser_men",
    },

    "marfy_all": {
        "marfy_handmade_precut",
    },

    "simplicity_all": {
        "simplicity_women",
        "simplicity_men",
    },

    "vikisews_all": {
        "vikisews_dresses",
        "vikisews_tops",
        "vikisews_pants",
        "vikisews_shirts",
        "vikisews_skirts",
        "vikisews_jackets",
        "vikisews_overalls",
        "vikisews_outerwear",
        "vikisews_homewear",
        "vikisews_men",
    },

    "shkatulka_all": {
        "shkatulka_dresses",
        "shkatulka_tops",
        "shkatulka_pants",
        "shkatulka_skirts",
        "shkatulka_hoodies",
        "shkatulka_outerwear",
        "shkatulka_jackets",
        "shkatulka_overalls",
        "shkatulka_homewear_women",
        "shkatulka_homewear_men",
        "shkatulka_men_shirts",
        "shkatulka_men_hoodies",
        "shkatulka_men_pants",
        "shkatulka_men_outerwear",
        "shkatulka_men_jackets",
    },

    "all_new": {
        "marfy_handmade_precut",

        "etsy_vogue_dresses",
        "etsy_vogue_tops",
        "etsy_vogue_blouses",
        "etsy_vogue_shirts",
        "etsy_vogue_skirts",
        "etsy_vogue_pants",
        "etsy_vogue_shorts",
        "etsy_vogue_jackets",
        "etsy_vogue_vests",
        "etsy_vogue_jumpsuits",
        "etsy_vogue_outerwear",
        "etsy_vogue_women",
        "etsy_vogue_men",

        "burdastyle_women_dresses",
        "burdastyle_women_tops",
        "burdastyle_women_bolero",
        "burdastyle_women_shirts",
        "burdastyle_women_sweaters",
        "burdastyle_women_blazers",
        "burdastyle_women_vests",
        "burdastyle_women_skirts",
        "burdastyle_women_pants",
        "burdastyle_women_shorts",
        "burdastyle_women_overalls",
        "burdastyle_women_suits",
        "burdastyle_women_outerwear",
        "burdastyle_women_underwear",
        "burdastyle_women_swimwear",
        "burdastyle_women_homewear",

        "burdastyle_men_shirts",
        "burdastyle_men_sweaters",
        "burdastyle_men_blazers",
        "burdastyle_men_vests",
        "burdastyle_men_pants",
        "burdastyle_men_shorts",
        "burdastyle_men_overalls",
        "burdastyle_men_suits",
        "burdastyle_men_outerwear",
        "burdastyle_men_underwear",

        "helpersew_women",
        "helpersew_men",

        "grasser_women",
        "grasser_men",
    },
}