from __future__ import annotations

import os
from pathlib import Path
from urllib.parse import quote_plus

os.environ["NO_PROXY"] = "127.0.0.1,localhost,::1"
os.environ["no_proxy"] = "127.0.0.1,localhost,::1"

PACKAGE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = PACKAGE_DIR.parent

DETAILED_LOG_DIR = PACKAGE_DIR / "logs"
GENERAL_LOG_DIR = PROJECT_ROOT / "logs"

DATA_DIR = Path("data")
STATE_DIR = DATA_DIR / "_state"
DATASET_DIR = Path(os.getenv("DATASET_DIR", "dataset"))

DISCOVERED_FILE = STATE_DIR / "discovered_urls.jsonl"
ERRORS_FILE = STATE_DIR / "errors.jsonl"

SITE_ERROR_LIMIT = int(os.getenv("SITE_ERROR_LIMIT", "4"))

PLAYWRIGHT_HEADLESS = os.getenv("PLAYWRIGHT_HEADLESS", "true").lower() == "true"
PLAYWRIGHT_TIMEOUT_MS = int(os.getenv("PLAYWRIGHT_TIMEOUT_MS", "30000"))

VPN_SITES = {
    "simplicity",
    "etsy",
    "marfy",
    # "vikisews", если потом понадобится
}

ETSY_QUERY_MAP = {
    "etsy_vogue_dresses": "vogue sewing pattern dress",
    "etsy_vogue_tops": "vogue sewing pattern top",
    "etsy_vogue_blouses": "vogue sewing pattern blouse",
    "etsy_vogue_shirts": "vogue sewing pattern shirt",
    "etsy_vogue_skirts": "vogue sewing pattern skirt",
    "etsy_vogue_pants": "vogue sewing pattern pants",
    "etsy_vogue_shorts": "vogue sewing pattern shorts",
    "etsy_vogue_jackets": "vogue sewing pattern jacket",
    "etsy_vogue_vests": "vogue sewing pattern vest",
    "etsy_vogue_jumpsuits": "vogue sewing pattern jumpsuit",
    "etsy_vogue_outerwear": "vogue sewing pattern coat",
    "etsy_vogue_women": "vogue sewing pattern womens",
    "etsy_vogue_men": "vogue sewing pattern mens",
}





def build_etsy_search_url(query: str, page: int = 1) -> str:
    q = quote_plus(query)

    # первая страница БЕЗ page
    if page <= 1:
        return f"https://www.etsy.com/search?q={q}"

    # остальные — с pagination
    return f"https://www.etsy.com/search?q={q}&page={page}&ref=pagination"


SITE_SPECS: dict[str, dict] = {
    "simplicity_women": {
        "type": "browser",
        "handler": "simplicity",
        "site": "simplicity",
        "start_url": "https://simplicity.com/women-patterns/",
        "category": "women-patterns",
    },
    "simplicity_men": {
        "type": "browser",
        "handler": "simplicity",
        "site": "simplicity",
        "start_url": "https://simplicity.com/men-patterns/",
        "category": "men-patterns",
    },

    "vikisews_dresses": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/platja-i-sarafany/",
        "category": "platja-i-sarafany",
    },
    "vikisews_tops": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/khudi-futbolki-longslivy/",
        "category": "khudi-futbolki-longslivy",
    },
    "vikisews_pants": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/bryuki-dzhinsy-shorty/",
        "category": "bryuki-dzhinsy-shorty",
    },
    "vikisews_shirts": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/rubashki-bluzki-korsazhi/",
        "category": "rubashki-bluzki-korsazhi",
    },
    "vikisews_skirts": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/jubki/",
        "category": "jubki",
    },
    "vikisews_jackets": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/zhakety-kardigany-zhilety/",
        "category": "zhakety-kardigany-zhilety",
    },
    "vikisews_overalls": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/kombinezony/",
        "category": "kombinezony",
    },
    "vikisews_outerwear": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/verhnjaja-odezhda/",
        "category": "verhnjaja-odezhda",
    },
    "vikisews_homewear": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/belye-domashnyaya-odezhda/",
        "category": "belye-domashnyaya-odezhda",
    },
    "vikisews_men": {
        "type": "browser",
        "handler": "vikisews",
        "site": "vikisews",
        "start_url": "https://vikisews.com/vykrojki/muzhskie-vykrojki/",
        "category": "muzhskie-vykrojki",
    },

    "shkatulka_dresses": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/platya/",
        "category": "platya",
        "section_gender": "women",
    },
    "shkatulka_tops": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bluzki-topy/",
        "category": "bluzki-topy",
        "section_gender": "women",
    },
    "shkatulka_pants": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bryuki1/",
        "category": "bryuki1",
        "section_gender": "women",
    },
    "shkatulka_skirts": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/yubki-2/",
        "category": "yubki-2",
        "section_gender": "women",
    },
    "shkatulka_hoodies": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/tolstovki-svitshoty-hudi/",
        "category": "tolstovki-svitshoty-hudi",
        "section_gender": "women",
    },
    "shkatulka_outerwear": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/verhnyaya-odejda/",
        "category": "verhnyaya-odejda",
        "section_gender": "women",
    },
    "shkatulka_jackets": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/jakety-jilety/",
        "category": "jakety-jilety",
        "section_gender": "women",
    },
    "shkatulka_overalls": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/kombinezony-polukombinezony/",
        "category": "kombinezony-polukombinezony",
        "section_gender": "women",
    },
    "shkatulka_homewear_women": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bele-kupalniki-domashnyaya-odejda/",
        "category": "bele-kupalniki-domashnyaya-odezhda",
        "section_gender": "women",
    },
    "shkatulka_homewear_men": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bele-domashnyaya-odejda/",
        "category": "bele-domashnyaya-odezhda",
        "section_gender": "men",
    },
    "shkatulka_men_shirts": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/rubashki-futbolki/",
        "category": "rubashki-futbolki",
        "section_gender": "men",
    },
    "shkatulka_men_hoodies": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/tolstovki-hudi-2/",
        "category": "tolstovki-hudi-2",
        "section_gender": "men",
    },
    "shkatulka_men_pants": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/bryuki-shorty/",
        "category": "bryuki-shorty",
        "section_gender": "men",
    },
    "shkatulka_men_outerwear": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/verhnyaya-odejda-3/",
        "category": "verhnyaya-odejda-3",
        "section_gender": "men",
    },
    "shkatulka_men_jackets": {
        "type": "browser",
        "handler": "shkatulka",
        "site": "shkatulka",
        "start_url": "https://shkatulka-sew.ru/category/jilety-pidjaki/",
        "category": "jilety-pidjaki",
        "section_gender": "men",
    },

    "marfy_handmade_precut": {
        "type": "browser",
        "handler": "marfy",
        "site": "marfy",
        "start_url": "https://www.marfy.it/en/the-marfy-hand-made-pre-cut-sewing-pattern/",
        "category": "the-marfy-hand-made-pre-cut-sewing-pattern",
        "page_from": 1,
        "page_to": 108,
    },

    "etsy_vogue_dresses": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_dresses"], 1),
        "category": "vogue-dresses",
        "query": ETSY_QUERY_MAP["etsy_vogue_dresses"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_tops": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_tops"], 1),
        "category": "vogue-tops",
        "query": ETSY_QUERY_MAP["etsy_vogue_tops"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_blouses": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_blouses"], 1),
        "category": "vogue-blouses",
        "query": ETSY_QUERY_MAP["etsy_vogue_blouses"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_shirts": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_shirts"], 1),
        "category": "vogue-shirts",
        "query": ETSY_QUERY_MAP["etsy_vogue_shirts"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_skirts": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_skirts"], 1),
        "category": "vogue-skirts",
        "query": ETSY_QUERY_MAP["etsy_vogue_skirts"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_pants": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_pants"], 1),
        "category": "vogue-pants",
        "query": ETSY_QUERY_MAP["etsy_vogue_pants"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_shorts": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_shorts"], 1),
        "category": "vogue-shorts",
        "query": ETSY_QUERY_MAP["etsy_vogue_shorts"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_jackets": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_jackets"], 1),
        "category": "vogue-jackets",
        "query": ETSY_QUERY_MAP["etsy_vogue_jackets"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_vests": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_vests"], 1),
        "category": "vogue-vests",
        "query": ETSY_QUERY_MAP["etsy_vogue_vests"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_jumpsuits": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_jumpsuits"], 1),
        "category": "vogue-jumpsuits",
        "query": ETSY_QUERY_MAP["etsy_vogue_jumpsuits"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_outerwear": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_outerwear"], 1),
        "category": "vogue-outerwear",
        "query": ETSY_QUERY_MAP["etsy_vogue_outerwear"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_women": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_women"], 1),
        "category": "vogue-women",
        "query": ETSY_QUERY_MAP["etsy_vogue_women"],
        "page_from": 1,
        "page_to": 250,
    },
    "etsy_vogue_men": {
        "type": "browser",
        "handler": "etsy",
        "site": "etsy",
        "start_url": build_etsy_search_url(ETSY_QUERY_MAP["etsy_vogue_men"], 1),
        "category": "vogue-men",
        "query": ETSY_QUERY_MAP["etsy_vogue_men"],
        "page_from": 1,
        "page_to": 250,
    },

    "burdastyle_women_dresses": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/platya-dlya-zhenshhin/",
        "category": "platya-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_tops": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/topy-dlya-zhenshhin/",
        "category": "topy-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_bolero": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/bolero-dlya-zhenshhin/",
        "category": "bolero-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_shirts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/rubashki-dlya-zhenshhin/",
        "category": "rubashki-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_sweaters": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/svitery-dlya-zhenshhin/",
        "category": "svitery-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_blazers": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/pidzhaki-dlya-zhenshhin/",
        "category": "pidzhaki-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_vests": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/zhilety-dlya-zhenshhin/",
        "category": "zhilety-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_skirts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/yubki-dlya-zhenshhin/",
        "category": "yubki-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_pants": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/bryuki-dlya-zhenshhin/",
        "category": "bryuki-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_shorts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/shorty-dlya-zhenshhin/",
        "category": "shorty-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_overalls": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/kombinezony-dlya-zhenshhin/",
        "category": "kombinezony-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_suits": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/komplekty-i-kostyumy-dlya-zhenshhin/",
        "category": "komplekty-i-kostyumy-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_outerwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/verkhnyaya-odezhda-dlya-zhenshhin/",
        "category": "verkhnyaya-odezhda-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_underwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/nizhnee-bele-dlya-zhenshhin/",
        "category": "nizhnee-bele-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_swimwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/kupalniki-dlya-zhenshhin/",
        "category": "kupalniki-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_women_homewear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/odezhda-dlya-doma-dlya-zhenshhin/",
        "category": "odezhda-dlya-doma-dlya-zhenshhin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_shirts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/rubashki-dlya-muzhchin/",
        "category": "rubashki-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_sweaters": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/svitery-dlya-muzhchin/",
        "category": "svitery-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_blazers": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/pidzhaki-dlya-muzhchin/",
        "category": "pidzhaki-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_vests": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/zhilety-dlya-muzhchin/",
        "category": "zhilety-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_pants": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/bryuki-dlya-muzhchin/",
        "category": "bryuki-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_shorts": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/shorty-dlya-muzhchin/",
        "category": "shorty-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_overalls": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/kombinezony-dlya-muzhchin/",
        "category": "kombinezony-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_suits": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/komplekty-i-kostyumy-dlya-muzhchin/",
        "category": "komplekty-i-kostyumy-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_outerwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/verkhnyaya-odezhda-dlya-muzhchin/",
        "category": "verkhnyaya-odezhda-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },
    "burdastyle_men_underwear": {
        "type": "browser",
        "handler": "burdastyle",
        "site": "burdastyle",
        "start_url": "https://burdastyle.ru/vikroyki/nizhnee-bele-dlya-muzhchin/",
        "category": "nizhnee-bele-dlya-muzhchin",
        "page_from": 1,
        "page_to": 999,
    },

    "helpersew_women": {
        "type": "browser",
        "handler": "helpersew",
        "site": "helpersew",
        "start_url": "https://helpersew.com/catalog/zhenskie/",
        "category": "zhenskie",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "helpersew_men": {
        "type": "browser",
        "handler": "helpersew",
        "site": "helpersew",
        "start_url": "https://helpersew.com/catalog/muzhskie/",
        "category": "muzhskie",
        "page_from": 1,
        "page_to": 1,
        "needs_pagination": False,
    },

    "grasser_women_outerwear": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/vykroyki-verkhney-odezhdy/",
        "category": "vykrojki-verkhney-odezhdy",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_jackets_vests": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/zhakety-i-zhilety/",
        "category": "zhakety-i-zhilety",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_blouses_shirts": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/bluzki-i-rubashki/",
        "category": "bluzki-i-rubashki",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_dresses": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/platya-i-sarafany/",
        "category": "platya-i-sarafany",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_sweatshirts": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/svitshoty/",
        "category": "svitshoty",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_tshirts_bodys_tops": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/vykrojki-futbolok-bodi-topov/",
        "category": "vykrojki-futbolok-bodi-topov",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_pants_shorts_overalls": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/bryuki-shorty-kombinezony/",
        "category": "bryuki-shorty-kombinezony",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_skirts": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/yubki/",
        "category": "yubki",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_underwear_swimwear": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/nizhnee-bele-i-kupalniki/",
        "category": "nizhnee-bele-i-kupalniki",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },
    "grasser_women_swimwear": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/vykroyki-kupalnikov/",
        "category": "vykroyki-kupalnikov",
        "page_from": 1,
        "page_to": 999,
        "needs_pagination": True,
    },

    "grasser_men_outerwear": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/verkhnyaya-odezhda/",
        "category": "verkhnyaya-odezhda",
        "page_from": 1,
        "page_to": 1,
        "needs_pagination": False,
    },
    "grasser_men_jackets_vests": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/pidzhaki-i-zhilety/",
        "category": "pidzhaki-i-zhilety",
        "page_from": 1,
        "page_to": 1,
        "needs_pagination": False,
    },
    "grasser_men_shirts": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/muzhskie-rubashki/",
        "category": "muzhskie-rubashki",
        "page_from": 1,
        "page_to": 1,
        "needs_pagination": False,
    },
    "grasser_men_sweatshirts_hoodies": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/svitshoty-khudi-tolstovki-svitery/",
        "category": "svitshoty-khudi-tolstovki-svitery",
        "page_from": 1,
        "page_to": 1,
        "needs_pagination": False,
    },
    "grasser_men_pants_shorts": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/bryuki-shorty/",
        "category": "bryuki-shorty",
        "page_from": 1,
        "page_to": 1,
        "needs_pagination": False,
    },
    "grasser_men_homewear": {
        "type": "browser",
        "handler": "grasser",
        "site": "grasser",
        "start_url": "https://grasser.ru/vykrojki/domashnyaya-odezhda-i-aksessuary/",
        "category": "domashnyaya-odezhda-i-aksessuary",
        "page_from": 1,
        "page_to": 1,
        "needs_pagination": False,
    },
}

SPEC_GROUPS: dict[str, set[str]] = {
    "current_all": {
        "simplicity_women",
        "simplicity_men",
        "vikisews_dresses",
        "vikisews_tops",
        "vikisews_pants",
        "vikisews_shirts",
        "vikisews_skirts",
        "vikisews_jackets",
        "vikisews_overalls",
        "vikisews_outerwear",
        "vikisews_homewear",
        "vikisews_men",
        "shkatulka_dresses",
        "shkatulka_tops",
        "shkatulka_pants",
        "shkatulka_skirts",
        "shkatulka_hoodies",
        "shkatulka_outerwear",
        "shkatulka_jackets",
        "shkatulka_overalls",
        "shkatulka_homewear_women",
        "shkatulka_homewear_men",
        "shkatulka_men_shirts",
        "shkatulka_men_hoodies",
        "shkatulka_men_pants",
        "shkatulka_men_outerwear",
        "shkatulka_men_jackets",
    },
    "vpn_new": {
        "marfy_handmade_precut",
        "etsy_vogue_dresses",
        "etsy_vogue_tops",
        "etsy_vogue_blouses",
        "etsy_vogue_shirts",
        "etsy_vogue_skirts",
        "etsy_vogue_pants",
        "etsy_vogue_shorts",
        "etsy_vogue_jackets",
        "etsy_vogue_vests",
        "etsy_vogue_jumpsuits",
        "etsy_vogue_outerwear",
        "etsy_vogue_women",
        "etsy_vogue_men",
    },
    "novpn_new": {
        key for key, spec in SITE_SPECS.items()
        if spec["site"] in {"burdastyle", "helpersew", "grasser"}
    },
    "burda_all": {
        key for key, spec in SITE_SPECS.items()
        if spec["site"] == "burdastyle"
    },
    "helpersew_all": {
        key for key, spec in SITE_SPECS.items()
        if spec["site"] == "helpersew"
    },
    "grasser_all": {
        key for key, spec in SITE_SPECS.items()
        if spec["site"] == "grasser"
    },
    "etsy_all": {
        key for key, spec in SITE_SPECS.items()
        if spec["site"] == "etsy"
    },
    "all_new": {
        key for key, spec in SITE_SPECS.items()
        if spec["site"] in {"marfy", "etsy", "burdastyle", "helpersew", "grasser"}
    },
}